version: "3"

services:
  web:
    container_name: ngi_ricetta_backend
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 8095:80
    links:
      - app
  app:
    container_name: php_app_ricetta_backend
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 9000:9000
    links:
      - db
    environment:
      - VIRTUAL_HOST=ricetta-backend
      - DB_PORT=3306
      - DB_HOST=db
      - DB_CONNECTION=mysql
  db:
    container_name: mysql_ricetta_backend
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:9090

networks:
  default:
    external:
      name: nginx-proxy2
